import React, { useEffect, useMemo, useState } from 'react';
import './riddle-studio.css';
import './riddle-progress.css';

const LANGUAGES = ['English', 'Telugu', 'Hindi', 'Tamil', 'Kannada', 'Malayalam'];
const STORAGE_KEY = 'pattan-riddle-studio-v1';
function loadSaved(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')}catch{return null}}
function downloadJson(data){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`riddle-video-${Date.now()}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),500)}

export default function RiddleStudio(){
  const saved=useMemo(loadSaved,[]);
  const [form,setForm]=useState(saved?.form||{language:'English',count:15,duration:12,thinkingSeconds:12,difficulty:'Easy to medium',audience:'Family audience, ages 13–35',theme:'Mixed clever riddles'});
  const [data,setData]=useState(saved?.data||null);const [busy,setBusy]=useState(false);const [status,setStatus]=useState('Local AI is ready. No API key is required.');
  const [progress,setProgress]=useState({stage:'idle',elapsedSeconds:0,generatedCharacters:0});
  useEffect(()=>{if(typeof window.electronAPI?.onRiddleGenerationProgress!=='function')return undefined;return window.electronAPI.onRiddleGenerationProgress(next=>setProgress(next||{}))},[]);
  const updateForm=(key,value)=>setForm(current=>({...current,[key]:value}));
  const updateRiddle=(index,key,value)=>setData(current=>({...current,riddles:current.riddles.map((item,i)=>i===index?{...item,[key]:value}:item)}));
  const generate=async()=>{if(typeof window.electronAPI?.generateRiddlePackage!=='function'){setStatus('Restart Voice Presentator once to activate the integrated local generator.');return}setBusy(true);setProgress({stage:'starting',elapsedSeconds:0,generatedCharacters:0});setStatus(`Local AI is writing and checking ${form.count} ${form.language} riddles…`);try{const result=await window.electronAPI.generateRiddlePackage(form);if(!result?.ok||!result.package)throw new Error(result?.error||'No riddle package was returned.');setData(result.package);localStorage.setItem(STORAGE_KEY,JSON.stringify({form,data:result.package}));setStatus(`Production package ready using ${result.model||'local AI'}. Review every answer before publishing.`);setProgress(current=>({...current,stage:'complete'}))}catch(error){setStatus(`Generation stopped: ${error.message}`);setProgress(current=>({...current,stage:'error'}))}finally{setBusy(false)}};
  const copyAll=async()=>{if(!data)return;await navigator.clipboard.writeText(JSON.stringify(data,null,2));setStatus('Complete production package copied.')};
  return <div className="rs-shell"><aside className="rs-controls"><div className="rs-kicker">VOICE PRESENTATOR</div><h1>Riddle Studio</h1><p className="rs-sub">Long-form 16:9 YouTube production</p>
    <label>Language<select value={form.language} onChange={e=>updateForm('language',e.target.value)}>{LANGUAGES.map(language=><option key={language}>{language}</option>)}</select></label>
    <div className="rs-pair"><label>Riddles<input type="number" min="1" max="20" value={form.count} onChange={e=>updateForm('count',Math.max(1,Math.min(20,Number(e.target.value)||1)))}/></label><label>Minutes<input type="number" min="1" max="30" value={form.duration} onChange={e=>updateForm('duration',Math.max(1,Math.min(30,Number(e.target.value)||1)))}/></label></div>
    <label>Thinking time (seconds)<input type="number" min="5" max="30" value={form.thinkingSeconds} onChange={e=>updateForm('thinkingSeconds',Number(e.target.value))}/></label>
    <label>Difficulty<select value={form.difficulty} onChange={e=>updateForm('difficulty',e.target.value)}><option>Easy</option><option>Easy to medium</option><option>Medium</option><option>Medium to hard</option></select></label>
    <label>Audience<input value={form.audience} onChange={e=>updateForm('audience',e.target.value)}/></label><label>Theme<textarea value={form.theme} onChange={e=>updateForm('theme',e.target.value)}/></label>
    <button className="rs-generate" disabled={busy} onClick={generate}>{busy?'Generating locally…':'✦ Generate video package'}</button><div className="rs-local">● Local AI · no API key</div></aside>
    <main className="rs-workspace"><div className={`rs-status ${status.includes('stopped')?'error':''}`}>{status}</div>{busy&&<div className="rs-progress" role="status" aria-live="polite"><div className="rs-spinner"></div><div className="rs-progress-copy"><strong>{progress.stage==='loading'?'Loading the local AI model…':progress.stage==='writing'?'Writing and validating riddles…':'Starting local generation…'}</strong><span>{progress.elapsedSeconds||0}s elapsed · {(progress.generatedCharacters||0).toLocaleString()} characters generated</span><div className="rs-progress-track"><i style={{width:`${Math.max(8,Math.min(94,(progress.generatedCharacters||0)/20))}%`}}/></div><small>Keep Voice Presentator open. Local CPU generation can take a few minutes.</small></div></div>}{!data?<div className="rs-empty"><div>?</div><h2>Create a complete riddle video</h2><p>Choose a language and settings. English is selected by default.</p></div>:<><header className="rs-result-head"><div><span>PRODUCTION PACKAGE</span><input className="rs-title" value={data.title||''} onChange={e=>setData({...data,title:e.target.value})}/></div><div><button onClick={copyAll}>Copy all</button><button onClick={()=>downloadJson(data)}>Download JSON</button></div></header>
    <section className="rs-meta"><b>Thumbnail:</b> {data.thumbnailText}<br/><br/><b>Intro:</b> {data.intro}<br/><br/><b>Outro:</b> {data.outro}<br/><br/><b>Description:</b> {data.description}<br/><br/>{(data.hashtags||[]).join(' ')}</section>
    <section className="rs-list">{(data.riddles||[]).map((riddle,index)=><article className="rs-card" key={`${riddle.number}-${index}`}><div className="rs-card-head"><strong>Riddle {riddle.number||index+1}</strong><span>◷ {riddle.thinkingSeconds||form.thinkingSeconds}s</span></div><label>Question<textarea value={riddle.question||''} onChange={e=>updateRiddle(index,'question',e.target.value)}/></label><div className="rs-pair wide"><label>Answer<input value={riddle.answer||''} onChange={e=>updateRiddle(index,'answer',e.target.value)}/></label><label>Explanation<textarea value={riddle.explanation||''} onChange={e=>updateRiddle(index,'explanation',e.target.value)}/></label></div><details><summary>Voice-over and screen text</summary><label>Voice-over<textarea value={riddle.voiceover||''} onChange={e=>updateRiddle(index,'voiceover',e.target.value)}/></label><label>Screen text<textarea value={riddle.screenText||''} onChange={e=>updateRiddle(index,'screenText',e.target.value)}/></label></details><details><summary>Flow 16:9 prompt</summary><textarea className="rs-flow" value={riddle.flowPrompt||''} onChange={e=>updateRiddle(index,'flowPrompt',e.target.value)}/><button onClick={()=>navigator.clipboard.writeText(riddle.flowPrompt||'')}>Copy Flow prompt</button></details><div className="rs-check">✓ {riddle.qualityCheck||'Review answer before publishing.'}</div></article>)}</section></>}</main></div>
}
