import React, { useEffect, useMemo, useRef, useState } from 'react';
import './video-resizer.css';

const RATIOS = {
  '9:16': [[1080,1920],[720,1280],[2160,3840]],
  '16:9': [[1920,1080],[1280,720],[3840,2160]],
  '1:1': [[1080,1080],[2160,2160]],
  '4:5': [[1080,1350]], '4:3': [[1440,1080]], '3:4': [[1080,1440]],
  '21:9': [[2560,1080],[3440,1440]], Custom: [[1080,1920]]
};
const ALL_RATIOS = ['1:1','9:16','16:9','4:5','4:3','3:4','21:9'];
const defaults = { ratio:'9:16', width:1080, height:1920, mode:'mobile-fill', format:'mp4', codec:'h264', fps:'original', quality:'high', crf:18, audio:'original', color:'#000000', blur:28, zoom:0, x:50, y:50, rotation:0, flipH:false, flipV:false, guides:'none' };
const fileUrl = value => encodeURI(`file:///${String(value || '').replace(/\\/g, '/')}`).replace(/#/g,'%23').replace(/\?/g,'%3F');

export default function VideoResizer() {
  const [source,setSource]=useState(null), [settings,setSettings]=useState(defaults);
  const [jobs,setJobs]=useState([]), [busy,setBusy]=useState(false), [error,setError]=useState('');
  const [compare,setCompare]=useState(false), [currentTime,setCurrentTime]=useState(0);
  const activeJob=useRef('');
  const patch=(key,value)=>setSettings(current=>({...current,[key]:value}));
  const orientationMismatch=Boolean(source&&((source.height>source.width&&settings.width>settings.height)||(source.width>source.height&&settings.height>settings.width)));
  const protectedExtension=orientationMismatch&&['smart-crop','auto','extender','expand'].includes(settings.mode);
  const effectivePreviewMode=orientationMismatch&&['smart-crop','auto','expand'].includes(settings.mode)?'expand':protectedExtension?'extender':settings.mode;
  const previewStyle=useMemo(()=>({ objectFit:['mobile-fill','crop','smart-crop','auto'].includes(effectivePreviewMode)?'cover':'contain', objectPosition:`${settings.x}% ${settings.y}%`, transform:`scale(${1+settings.zoom/100}) rotate(${settings.rotation}deg) scaleX(${settings.flipH?-1:1}) scaleY(${settings.flipV?-1:1})` }),[settings,effectivePreviewMode]);

  useEffect(()=>window.electronAPI?.onVideoResizerProgress?.(progress=>setJobs(current=>current.map(job=>job.jobId===progress.jobId?{...job,...progress,status:progress.percent===100?'Completed':'Processing'}:job))),[]);
  const choose=async()=>{ setError(''); const picked=await window.electronAPI?.videoResizerPickVideo?.(); if(!picked?.ok)return; const meta=await window.electronAPI.videoResizerProbe(picked.filePath); if(!meta?.ok){setError(meta?.error||'Video could not be opened.');return;} setSource(meta);setSettings(current=>{const landscapeToMobile=meta.width>meta.height&&current.height>current.width;const crossesOrientation=(meta.height>meta.width&&current.width>current.height)||landscapeToMobile;return crossesOrientation?{...current,mode:landscapeToMobile?'mobile-fill':'extender',zoom:0,x:50,y:50}:current;}); setCurrentTime(0); };
  const chooseRatio=ratio=>{const [width,height]=RATIOS[ratio][0];setSettings(current=>{const landscapeToMobile=Boolean(source&&source.width>source.height&&height>width);const crossesOrientation=Boolean(source&&((source.height>source.width&&width>height)||landscapeToMobile));return {...current,ratio,width,height,...(crossesOrientation?{mode:landscapeToMobile?'mobile-fill':'extender',zoom:0,x:50,y:50}:{})};});};
  const exportOne=async(custom={})=>{ if(!source)throw new Error('Upload a source video first.'); const options={...settings,...custom}; const jobId=crypto.randomUUID(); activeJob.current=jobId; const job={jobId,ratio:options.ratio,width:options.width,height:options.height,percent:0,status:'Waiting',phase:'Queued'};setJobs(current=>[job,...current]); const result=await window.electronAPI.videoResizerExport({jobId,inputPath:source.filePath,duration:source.duration,sourceWidth:source.width,sourceHeight:source.height,ratioName:options.ratio.replace(':','x'),...options,x:options.x/100,y:options.y/100}); if(!result?.ok){setJobs(current=>current.map(item=>item.jobId===jobId?{...item,status:'Failed',error:result?.error,phase:result?.error}:item));throw new Error(result?.error||'Export failed.');} setJobs(current=>current.map(item=>item.jobId===jobId?{...item,status:'Completed',percent:100,outputPath:result.outputPath,phase:'Validated and saved to Downloads'}:item)); return result; };
  const runCurrent=async()=>{setBusy(true);setError('');try{await exportOne();}catch(e){setError(e.message);}finally{setBusy(false);activeJob.current='';}};
  const runAll=async()=>{setBusy(true);setError('');try{for(const ratio of ALL_RATIOS){const [width,height]=RATIOS[ratio][0];await exportOne({ratio,width,height});}}catch(e){setError(e.message);}finally{setBusy(false);activeJob.current='';}};
  const cancel=async()=>{if(activeJob.current)await window.electronAPI?.videoResizerCancel?.(activeJob.current);setBusy(false);};
  const resolutions=RATIOS[settings.ratio]||[[settings.width,settings.height]];
  return <main className="vrm-shell">
    <header className="vrm-hero"><div><span>PROFESSIONAL WHOLE-VIDEO PROCESSING</span><h1>Video Ratio Master</h1><p>Resize, crop, reframe and export every frame at the selected real resolution.</p></div><div className="vrm-match">✓ PREVIEW MATCH<br/><small>Export uses current preview settings</small></div></header>
    <section className="vrm-grid">
      <aside className="vrm-controls">
        <div className="vrm-section"><h3>Source video</h3><button className="vrm-primary" onClick={choose}>＋ Upload Video</button>{source&&<div className="vrm-source"><b>{source.name}</b><small>{source.width}×{source.height} · {source.duration.toFixed(1)}s · {source.fps.toFixed(2)} FPS · {source.codec}</small></div>}</div>
        <div className="vrm-two"><label>Output ratio<select value={settings.ratio} onChange={e=>chooseRatio(e.target.value)}>{Object.keys(RATIOS).map(r=><option key={r}>{r}</option>)}</select></label><label>Resolution<select value={`${settings.width}x${settings.height}`} onChange={e=>{const [w,h]=e.target.value.split('x').map(Number);setSettings(s=>({...s,width:w,height:h}))}}>{resolutions.map(([w,h])=><option key={`${w}x${h}`} value={`${w}x${h}`}>{w}×{h}</option>)}</select></label></div>
        {settings.ratio==='Custom'&&<div className="vrm-two"><label>Width<input type="number" value={settings.width} onChange={e=>patch('width',Number(e.target.value))}/></label><label>Height<input type="number" value={settings.height} onChange={e=>patch('height',Number(e.target.value))}/></label></div>}
        <div className="vrm-two"><label>Resize mode<select value={settings.mode} onChange={e=>patch('mode',e.target.value)}><option value="mobile-fill">Mobile Full Screen — fill 9:16</option><option value="expand">Full Frame Expand — cover all</option><option value="extender">Extender — protect full subject</option><option value="fit">Fit — no crop</option><option value="crop">Crop — fill frame</option><option value="auto">Smart Auto-Fit</option><option value="smart-crop">Smart Auto-Crop + Protect</option><option value="blur">Blur Background</option><option value="mirror">Mirror Background</option></select></label><label>Background<input type="color" value={settings.color} onChange={e=>patch('color',e.target.value)}/></label></div>
        {protectedExtension&&<div className="vrm-protection">✓ FULL-FRAME PROTECTION ACTIVE — the complete video fills {settings.ratio}; faces and heads remain inside the output.</div>}
        <label>Zoom <b>{settings.zoom}%</b><input type="range" min="0" max="300" value={settings.zoom} onChange={e=>patch('zoom',Number(e.target.value))}/></label>
        <label>Horizontal position <b>{settings.x}%</b><input type="range" min="0" max="100" value={settings.x} onChange={e=>patch('x',Number(e.target.value))}/></label>
        <label>Vertical position <b>{settings.y}%</b><input type="range" min="0" max="100" value={settings.y} onChange={e=>patch('y',Number(e.target.value))}/></label>
        {settings.mode==='blur'&&<label>Blur strength <b>{settings.blur}</b><input type="range" min="4" max="80" value={settings.blur} onChange={e=>patch('blur',Number(e.target.value))}/></label>}
        <div className="vrm-three"><label>FPS<select value={settings.fps} onChange={e=>patch('fps',e.target.value)}>{['original','24','25','30','50','60'].map(v=><option key={v} value={v}>{v==='original'?'Original':v}</option>)}</select></label><label>Quality<select value={settings.quality} onChange={e=>patch('quality',e.target.value)}>{['fast','balanced','high','maximum'].map(v=><option key={v}>{v}</option>)}</select></label><label>Audio<select value={settings.audio} onChange={e=>patch('audio',e.target.value)}><option value="original">Original</option><option value="mute">Mute</option></select></label></div>
        <div className="vrm-three"><label>Format<select value={settings.format} onChange={e=>patch('format',e.target.value)}><option value="mp4">MP4</option><option value="mov">MOV</option><option value="webm">WebM</option></select></label><label>Codec<select value={settings.codec} onChange={e=>patch('codec',e.target.value)}><option value="h264">H.264</option><option value="h265">H.265</option></select></label><label>Rotation<select value={settings.rotation} onChange={e=>patch('rotation',Number(e.target.value))}>{[0,90,180,270].map(v=><option key={v} value={v}>{v}°</option>)}</select></label></div>
        <label>CRF / quality <b>{settings.crf}</b><input type="range" min="10" max="40" value={settings.crf} onChange={e=>patch('crf',Number(e.target.value))}/></label>
        <div className="vrm-checks"><label><input type="checkbox" checked={settings.flipH} onChange={e=>patch('flipH',e.target.checked)}/> Mirror horizontally</label><label><input type="checkbox" checked={settings.flipV} onChange={e=>patch('flipV',e.target.checked)}/> Flip vertically</label></div>
        <div className="vrm-actions"><button onClick={runCurrent} disabled={!source||busy}>Export Current Ratio</button><button onClick={runAll} disabled={!source||busy}>Export All Ratios</button>{busy&&<button className="danger" onClick={cancel}>Cancel</button>}<button className="ghost" onClick={()=>setSettings(defaults)}>Reset All</button></div>{error&&<div className="vrm-error">{error}</div>}
      </aside>
      <section className="vrm-stage-column">
        <div className="vrm-preview-bar"><b>REAL OUTPUT PREVIEW · {settings.width}×{settings.height}</b><button onClick={()=>setCompare(v=>!v)}>{compare?'Single View':'Before / After'}</button><select value={settings.guides} onChange={e=>patch('guides',e.target.value)}><option value="none">No safe area</option><option value="shorts">Shorts safe area</option><option value="reels">Reels safe area</option><option value="youtube">YouTube safe area</option></select></div>
        <div className={`vrm-preview-wrap ${compare?'compare':''}`}>{compare&&source&&<div className="vrm-before"><span>ORIGINAL</span><video src={fileUrl(source.filePath)} controls/></div>}<div className="vrm-after" style={{aspectRatio:`${settings.width}/${settings.height}`,background:effectivePreviewMode==='fit'?settings.color:'#05070d'}}><span>OUTPUT</span>{source&&<>{['blur','mirror','extender'].includes(effectivePreviewMode)&&<video className="vrm-blur" src={fileUrl(source.filePath)} style={{objectPosition:`${settings.x}% ${settings.y}%`,filter:['blur','extender'].includes(effectivePreviewMode)?`blur(${settings.blur}px)`:'none',transform:effectivePreviewMode==='mirror'?'scale(1.15) scaleX(-1)':'scale(1.15)'}} muted/>}<video src={fileUrl(source.filePath)} controls style={effectivePreviewMode==='expand'?{...previewStyle,objectFit:'fill',transform:`rotate(${settings.rotation}deg) scaleX(${settings.flipH?-1:1}) scaleY(${settings.flipV?-1:1})`}:effectivePreviewMode==='extender'?{...previewStyle,objectFit:'contain',transform:`rotate(${settings.rotation}deg) scaleX(${settings.flipH?-1:1}) scaleY(${settings.flipV?-1:1})`}:previewStyle} onTimeUpdate={e=>setCurrentTime(e.currentTarget.currentTime)}/><div className={`vrm-safe ${settings.guides}`}/></>}</div></div>
        <div className="vrm-timeline"><div><b>{currentTime.toFixed(2)}s</b><span>{source?.duration?.toFixed(2)||'0.00'}s</span></div><input type="range" min="0" max={source?.duration||1} step="0.01" value={currentTime} readOnly/><small>Timeline · current frame · crop position X {settings.x}% · Y {settings.y}% · zoom {settings.zoom}%</small></div>
        <div className="vrm-queue"><h3>Export Queue</h3>{!jobs.length?<p>No exports queued.</p>:jobs.map(job=><article key={job.jobId} className={job.status.toLowerCase()}><div><b>{job.ratio} — {job.width}×{job.height}</b><small>{job.phase}</small></div><strong>{job.percent||0}%</strong><progress max="100" value={job.percent||0}/>{job.outputPath&&<button onClick={()=>window.electronAPI?.showItemInFolder?.(job.outputPath)}>Show file</button>}</article>)}</div>
      </section>
    </section>
  </main>;
}
